### ISSUE TITLE
sysf.lhs or SystemF.lhs?

### ISSUE THREAD

**Issue by mouse07410** [sweirich/challenge#6]
What happened to `says.lhs` (or any *other* LHS files) file that seems necessary for building documentation?

In `Makefile`:
```make
all:
	lhs2tex sysf.lhs > sysf.tex
	pdflatex sysf.tex
```

**Comment by sweirich** [comment]
Sorry, that was an old version and this Makefile is not relevant any more.  The text has been migrated to the markdown files instead.
