### ISSUE TITLE
with ghc 8.10.2

### ISSUE THREAD

**Issue by ilitzroth** [sweirich/challenge#9]
> challenge/debruijn$ cabal build
src/Imports.hs:30:1: error:
    Could not find module ‘Data.Singletons.Prelude.Eq’
    Perhaps you meant Data.Singletons.Decide (from singletons-3.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import Data.Singletons.Prelude.Eq
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Imports.hs:31:1: error:
    Could not find module ‘Data.Singletons.Prelude.Enum’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import Data.Singletons.Prelude.Enum
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Imports.hs:32:1: error:
    Could not find module ‘Data.Singletons.Prelude.Num’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
32 | import Data.Singletons.Prelude.Num
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Imports.hs:33:1: error:
    Could not find module ‘Data.Singletons.Prelude’
    Perhaps you meant
      Data.Singletons.Decide (from singletons-3.0)
      Data.Singletons.Bool (needs flag -package-key singleton-bool-0.1.5)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
33 | import Data.Singletons.Prelude
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Imports.hs:34:1: error:
    Could not find module ‘Data.Singletons.TH’
    Perhaps you meant
      Data.Singletons (from singletons-3.0)
      Data.Singletons.Bool (needs flag -package-key singleton-bool-0.1.5)
      Data.Singletons.Sigma (from singletons-3.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
34 | import Data.Singletons.TH
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sweirich** [comment]
Singletons 3.0 is not compatible with this version. I've added an upper bound to the cabal file to restrict to version 2.6 or 2.7. (I've tested locally with stack lts-15.14, which includes GHC 8.10.4.)
